name: pethero
description: Um protótipo de aplicativo para uma ONG de animais

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  # Utils
  equatable: 2.0.3
  flutter_svg: 0.23.0+1
  dartz: 0.10.0
  path_provider: 2.0.7
  path: 1.8.0
  package_info: 2.0.2
  device_info: 2.0.3
  version: 2.0.0

  # Local DB
  hive: ^2.1.0
  hive_flutter: 1.1.0

  # Permission
  permission_handler: 8.3.0

  # Network
  connectivity_plus: 2.0.3
  dio: 4.0.4

  # State Management
  mobx: 2.0.7
  flutter_mobx: 2.0.5
  flutter_modular: 5.0.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.5
  mobx_codegen: 2.0.4
  mocktail: 0.2.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
